// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0gD6Pj5jEaJAwoZnB6d444jpeYnSQP-E',
    appId: '1:480737538286:web:d9a2865b0f77142c2e552b',
    messagingSenderId: '480737538286',
    projectId: 'saftyeye-16eb2',
    authDomain: 'saftyeye-16eb2.firebaseapp.com',
    storageBucket: 'saftyeye-16eb2.appspot.com',
    measurementId: 'G-JKXNZ6G5GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIiZLT1a5ZhWqbPfjx_vUiN1czPgVVrUA',
    appId: '1:480737538286:android:c564c98b54278ad22e552b',
    messagingSenderId: '480737538286',
    projectId: 'saftyeye-16eb2',
    storageBucket: 'saftyeye-16eb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKRLWSMj27IChGXF5bCfeFfeeLc8kATdI',
    appId: '1:480737538286:ios:b0db1122dd2c77922e552b',
    messagingSenderId: '480737538286',
    projectId: 'saftyeye-16eb2',
    storageBucket: 'safetyeye-e9274.appspot.com',
    iosBundleId: 'com.example.appTamplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKRLWSMj27IChGXF5bCfeFfeeLc8kATdI',
    appId: '1:480737538286:ios:f8dd5b5d01e5f8862e552b',
    messagingSenderId: '480737538286',
    projectId: 'safetyeye-e9274',
    storageBucket: 'safetyeye-e9274.appspot.com',
    iosBundleId: 'com.example.appTamplate.RunnerTests',
  );
}
